/*
Get_Collars Rebuild
Lets try to make some sense this time, eh?

Script Name: Get_Collars.js
Author: William Dowling
Build Date: 26 May, 2016
Description: Locate and grab updated collars from network to
				replace outdated Made In USA Collars
Build Number: 1.000

Ideas to implement:
	Push all gathered data into a JSON object for optimal
		handling of commands.
	Gather all relevant data before altering anything.

Progress:

	Version: 1.001
		26 May, 2016
		Continue with rebuild from original mangled mess.
		Including much more robust error handling and thorough comments.
		isTemplate function needs comments/descriptions
		not working as of save. need to improve the flow of control
		SIMPLIFY!!!

	Version: 1.002
		26 May, 2016
		Working from home.
		Simplifying functions. Broke down isTemplate to simply return
			true if at least 1 instance of a template is found, else return false.
		Built generic error reporting function that should be fully scalable.
		getTemplates function runs if isTemplate = true. returns array of template layers.
		findUSACollars function runs if there were no prior errors. populates and returns
			an array of all USA Collars in the document.
		Fixed flawed for in loops. stick to regular c style for loops.
		Currently working to populate all usa collars in array

	Version: 1.003
		27 May, 2016
		Added getObjectData function to populate theDocument objectf
		Added library object to hold placement coords and network paths
		Needs to be tested
		Should be working up to the point of populating theDocument object.
		*Update* - Tested on 31 May, fixed a couple of typos and all is working well.

	Version: 1.004
		31 May, 2016
		Moved the creation of the USA Collars layer to a later function to prevent a
			layer being created unnecessarily.
		Created function to move all usa collars to USA Collars layer, send layer to back and hide
		Tested and currently working for one or more scriptable templates

	Version: 1.005
		31 May, 2016
		Writing functions to go to network and grab DR Collars from template files.
		Added styleNum key to theDocument object
		Script is currently working all the way up to placing and positioning collars onto a scriptable template.
		Still need to include a DR collars label.
		Still need to create the rest of the library entries.
		Still need to build script UI for non-scriptable templates.

	Version: 1.006
		31 May, 2016
		Move library object into data storage container
		Created script UI. Still needs to be trimmed down.
		Still need to update the way getObjectData reads the information generated by the script UI.

	Version: 1.007
		31 May, 2016
		Fixed getObjectData function to properly read input from either scriptable template or scriptUI.
		Still need to create DR Collars Label.
		Last thing to do is fill out library object with correct paths and coordinates

	Version: 1.008
		01 June, 2016
		Removed a lot of fluff and extra, unnecessary stuff.
		Populated library object with correct paths and coordinates.
		Added DR Label creation and placement.
		


*/

function container()
{
	
	///////Begin/////////
	///Logic Container///
	/////////////////////

	function isTemplate(layers)
	{
		
		var result = false;
		
		try
		{
			//loop layers to find first instance
			//of a layer name that contains "FD"
			for(var a=0;a<layers.length;a++)
			{
				if(layers[a].name.indexOf("FD")>-1)
					result = true;
					break;
			}

			return result;
		}
		catch(e)
		{
			result = false;
			valid = false;
			errorList.push(mrap);
		}

		return result;
	}

	function getTemplates(layers)
	{
		var templateList = [];
		try
		{
			//loop layers and find all instances of
			//"FD". Push true results to templateList array
			for(var a=0;a<layers.length;a++)
			{
				var thisName = layers[a].name;
				if(thisName.indexOf("FD")>-1)
				{
					if(thisName.indexOf("MH")<0 && thisName.indexOf("WH")<0 && thisName.indexOf("YH")<0)
						templateList.push(layers[a]);
				}
			}
		}
		catch(e)
		{
			errorList.push(mrap);
			valid = false;
			return null;
		}

		return templateList;
	}

	function findUSACollars(collarLoc, templateList)
	{
		//findUSACollars function description

		//collarLoc argument should be a string
		//are collars located in the current selection or in a template layer?

		//"sel" - indicates the file is not a scriptable template
		// 		and collars must be selected at run-time

		//"template" - indicates file is a scriptable template
		//		top level layers are looped to find usa collars
		// 		and push all collars to usaCollars array.

		//templateList argument is an array of verified template layers.
		//only necessary if collarLoc == "template";

		var usaCollars = [];

		//try to populate usaCollars array
		//push errors to errorList
		try
		{
			//file is not a template.
			//loop the selection to move all
			//usa collars to usaCollars array
			if(collarLoc == "sel")
			{
				if(docRef.selection.length < 1)
				{
					errorList.push("Since this isn't a scriptable template, you must select the USA Collars first. Then re-run the script.");
					valid = false;
					return;
				}
				for(var a=0;a<docRef.selection.length;a++)
				{
					usaCollars.push(docRef.selection[a])
				}
			}


			//file contains at least one template.
			//loop the template layers and 
			//populate the usaCollars array
			else if(collarLoc == "template")
			{
				for(var a=0;a<templateList.length;a++)
				{
					var curTemplate = templateList[a];
					var prepress = curTemplate.layers["Prepress"];
					for(var b=0;b<prepress.layers.length;b++)
					{
						var curSize = prepress.layers[b];
						for(var c=0;c<curSize.groupItems.length;c++)
						{
							if(curSize.groupItems[c].name.indexOf("Collar")>-1)
							{
								usaCollars.push(curSize.groupItems[c]);
								break;
							}
						}
					}
				}
			}
		}
		catch(e)
		{
			errorList.push("Failed while attempting to populate usaCollars array.");
			return;
		}

		return usaCollars;
	}

	function getObjectData(thisTemplate, library)
	{
		//function description
		//retrieve necessary data from thisTemplate variable (layer)
		//and populate result object.

		var result = {};
		
		// try to populate result object
		//if existTemplateLayer, this is a scriptable template.
		//pull information from layer name
		if(existTemplate)	
		{
			var thisTempText = thisTemplate.name;
		}
		else
		{
			var thisTempText = thisTemplate;
		}
		try{
			var theCode = thisTempText.substring(0,thisTempText.indexOf("_0"));
			result.code = thisTempText.substring(0,thisTempText.indexOf("_0"));
			result.styleNum = thisTempText.substring(thisTempText.indexOf("_0")+1,thisTempText.length);
			result.coords = library[theCode]["coords"];
			result.path = library[theCode]["path"];


			return result;
		}
		catch(e)
		{
			errorList.push(mrap + "\n getObjectData failure")
			valid = false;
			return;
		}
		
	}

	function moveUSACollars(collars)
	{

		//check if there are any usa collars to move

		if(collars.length < 1)
		{
			errorList.push("There aren't any USA Collars to move.\nEither the collars have already been moved, or this is not a scriptable template and you don't have any collars selected!");
			valid = false;
			return;
		}
		//create or identify USA Collars layer

		try
		{
			//check if USA Collars layer exists already
			//create one if it does not exist
			try
			{
				//USA Collars layer exists
				var usaLayer = docRef.layers["USA Collars"];
			}
			catch(e)
			{
				//create USA Collar layer
				var usaLayer = docRef.layers.add();
				usaLayer.name = "USA Collars";
			}
		}
		catch(e)
		{
			errorList.push("Failed while attempting to create/identify USA Collars Layer.");
			valid = false;
			return;
		}

		//try to move all collars
		try
		{
			for each(collar in collars)
				collar.moveToBeginning(usaLayer);
			usaLayer.zOrder(ZOrderMethod.SENDTOBACK);
			usaLayer.visible = false;
		}
		catch(e)
		{
			errorList.push("Failed while attempting to move collars to USA Collars Layer.");
			valid = false;
			return;
		}
	}

	function getNewCollars(code,path,coords,style)
	{
		//open template from network

		var source = new File(path + code + "_" + style + ".ait")
		var sourceDoc = app.open(source);
		var sourcePrepress = sourceDoc.layers[code + "_" + style].layers["Prepress"];

		//establish destination 

		if(existTemplate)
		{
			var dest = docRef.layers[code + "_" + style].layers["Prepress"];
			var labelDest = docRef.layers[code + "_" + style].layers["Mockup"];
		}
		else
			try
			{
				var dest = docRef.layers["Artwork"];
				var labelDest = docRef.layers["Artwork"];
			}
			catch(e)
			{
				var dest = docRef.layers[0];
				var labelDest = docRef.layers[0];
			}
		try
		{ 
			dest.locked = false;
			dest.visible = true;
		}
		catch(e)
		{
			errorList.push(mrap + "\n getNewCollars failure!\nfailed trying to unlock/unhide layers.");
			valid = false;
			return;
		}

		//duplicate collars to prepress

		var sourceCollar;
		var curSize;
		var collarDest;

		for(var a=0;a<sourcePrepress.layers.length;a++)
		{
			curSize = sourcePrepress.layers[a].name;
			sourceCollar = sourcePrepress.layers[a].groupItems[curSize + " Collar"];

			if(dest.name.indexOf("Prepress") > -1)
				collarDest = dest.layers[curSize];
			else
				collarDest = dest;

			var copiedCollar = sourceCollar.duplicate(collarDest);
			copiedCollar.left = coords[curSize][0];
			copiedCollar.top = coords[curSize][1];
			copiedCollar.selected = true;
		}

		docRef.activate();

		var drLabel = labelDest.textFrames.add();
		drLabel.textRange.characterAttributes.size = 35;
		drLabel.contents = "DR Collars";
		drLabel.left = coords["Label"][0];
		drLabel.top = coords["Label"][1];
	}

	function whichGarments()
	{
		//Script UI window to prompt user for garment info for non-scriptable prepresses

		var sports = ["SLOW_SS", "SLOWW_SS", "SLOWY_SS", "FAST_SL", "FAST_RB", "FAST_FB_SL", "FAST_FB_SS", //
		"FAST_2B_SS", "BASE_FB_SL", "BASE_FB_Y_SL", "BASE_FB_SS","BASE_FB_Y_SS", "BASE_2B_SS", "BASE_2B_Y_SS"];

		var result;
		

		var wS = new Window("dialog", "What Collars Do You Need?");

		var inputGroup = wS.add("group");
			inputGroup.orientation = "column";
			var sportsGroup = inputGroup.add("group");
				sportsGroup.add("statictext", undefined, "Choose Sport");

				//populate sports dropdown list
				var sportsList = sportsGroup.add("dropdownlist", undefined, sports);
				sportsList.selection = 0;

			var styleGroup = inputGroup.add("group");

				styleGroup.add("statictext", undefined, "Enter Style Number:");

				//input text box for style number
				var styleInput = styleGroup.add("edittext", undefined, "000");

		var buttonGroup = wS.add("group");
			var submitButton = buttonGroup.add("button", undefined, "Submit");
			submitButton.onClick = function()
			{
				var thisResult = "";
				thisResult = "FD_" + sportsList.selection.text + "_" + styleInput.text;
				wS.close();
				result = thisResult;
			}
			var doneButton = buttonGroup.add("button", undefined, "I'm Finished");
			doneButton.onClick = function()
			{
				cont = false;
				wS.close();
				result = null;
			}


		wS.show();

		return result;
		

	}


	function sendErrors(errorList)
	{
		var errorString = "The Following Errors Occurred:\n";

		for(var a=0;a<errorList.length;a++)
		{
			errorString += errorList[a] + "\n";
		}
		alert(errorString);
	}




	////////End//////////
	///Logic Container///
	/////////////////////


	///////Begin////////
	////Data Storage////
	////////////////////

	var library =
			{
				//this object stores all relevant data for the network
				//location and placement coords of DR collars
				"FD_SLOW_SS" : 
				{
					"path": "/Volumes/Customization/Library/cads/prepress/FD_SLOW_SS/ConvertedTemplates/FD_SLOW_SS/",
					"coords" : 
					{
						"XS" : [-1133.12,625.48],
						"S" : [-1135.37,366.12],
						"M" : [-1137.62,101.68],
						"L" : [-1139.87,-172.14],
						"XL" : [-1141.67,-453.05],
						"2XL" : [-1144.37,-740.87],
						"3XL" : [-1146.62,-1036.67],
						"4XL" : [-1148.87,-1339.05],
						"5XL" : [-1151.12,-1648.31],
						"Label" : [-1142.64,744.73]
					}
				},      
				"FD_SLOWW_SS" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_SLOW_SS/ConvertedTemplates/FD_SLOWW_SS/",
					"coords" : 
					{
						"XXS" : [-904.86,482],
						"XS" : [-906.86,242],
						"S" : [-908.86,-5],
						"M" : [-910.86,-257],
						"L" : [-912.86,-517],
						"XL" : [-914.86,-784],
						"2XL" : [-916.86,-1055],
						"3XL" : [-918.86,-1330],
						"Label" : [-954.86,601.25]
					}
				},
				"FD_SLOWY_SS" :
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_SLOW_SS/ConvertedTemplates/FD_SLOWY_SS/",
					"coords" : 
					{
						"YXS" : [-803.12,-39.21],
						"YS" : [-807.12,-238.73],
						"YM" : [-809.12,-448],
						"YL" : [-813.12,-668.66],
						"YXL" : [-817.12,-900.07],
						"Label" : [-853.12,80.04]
					}
				},
				"FD_FAST_RB" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_FAST_RB/Converted_Templates/",
					"coords" : 
					{
						"XXS" : [-689.03,398.19],
						"XS" : [-690.83,158.31],
						"S" : [-692.63,-95.65],
						"M" : [-694.43,-359.71],
						"L" : [-696.23,-628.75],
						"XL" : [-696.23,-898.05],
						"2XL" : [-696.23,-1171.63],
						"3XL" : [-696.23,-1448.11],
						"Label" : [-688.55,517.44]
					}
				},
				"FD_FAST_SL" :
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_FAST_SL/Converted_Templates/",
					"coords" : 
					{
						"XXS" : [-689.03,398.19],
						"XS" : [-690.83,158.31],
						"S" : [-692.63,-95.65],
						"M" : [-694.43,-359.71],
						"L" : [-696.23,-628.75],
						"XL" : [-696.23,-898.05],
						"2XL" : [-696.23,-1171.63],
						"3XL" : [-696.23,-1448.11],
						"Label" : [-688.55,517.44]
					}
				} ,
				"FD_FAST_FB_SL" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_FAST_FB_SL/Converted_Templates/",
					"coords" : 
					{
						"XXS" : [-1034.26,509.1],
						"XS" : [-1035.26,255.1],
						"S" : [-1036.25,-5.2],
						"M" : [-1037.24,-273.1],
						"L" : [-1038.22,-548.32],
						"XL" : [-1039.21,-829.59],
						"2XL" : [-1040.18,-1115.33],
						"3XL" : [-1041.16,-1406.88],
						"Label" : [-1072.59,622.45]
					}
				},
				"FD_FAST_FB_SS" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_FAST_FB_SS/Converted_Templates/",
					"coords" : 
					{
						"XXS" : [-1130,436],
						"XS" : [-1131,181],
						"S" : [-1133,-78],
						"M" : [-1134,-341],
						"L" : [-1135,-613],
						"XL" : [-1135,-891],
						"2XL" : [-1136,-1174],
						"3XL" : [-1137,-1461],
						"Label" : [-1163.9,561.58]
					}
				},
				"FD_FAST_2B_SS" : 
				 {
					"path": "/Volumes/Customization/Library/cads/prepress/FD_FAST_2B_SS/Converted_Templates/",
					"coords" : 
					{
						"XXS" : [-1011.89,455.31],
						"XS" : [-1015.33,206.79],
						"S" : [-1018.88,-60.25],
						"M" : [-1022.12,-323.7],
						"L" : [-1025.7,-595.67],
						"XL" : [-1028.83,-879.72],
						"2XL" : [-1032.38,-1168.08],
						"3XL" : [-1035.83,-1457.79],
						"Label" : [-949.1,708.39]
					}
				},
				"FD_BASE_FB_SL" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_BASE_FB_SL/Converted_Templates/",
					"coords" : 
					{
						"S" : [-1112.95,697.41],
						"M" : [-1113.95,399.72],
						"L" : [-1113.95,93.16],
						"XL" : [-1113.95,-220.47],
						"2XL" : [-1113.95,-541.24],
						"3XL" : [-1114.95,-869.75],
						"4XL" : [-1114.95,-1200.86],
						"5XL" : [-1115.95,-1532.97],
						"Label" : [-1139.4,865.35]
					}
				},
				"FD_BASE_FB_Y_SL" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_BASE_FB_Y_SL/Converted_Templates/",
					"coords" : 
					{
						"YS" : [-846.33,-86.59],
						"YM" : [-846.33,-331.97],
						"YL" : [-846.33,-588],
						"YXL" : [-847.33,-855.2],
						"Label" : [-881.36,50.28]
					}
				},
				"FD_BASE_FB_SS" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_BASE_FB_SS/Converted_Templates/",
					"coords" : 
					{
						"S" : [-1234,618],
						"M" : [-1235,319],
						"L" : [-1235,13],
						"XL" : [-1236,-300],
						"2XL" : [-1236,-621],
						"3XL" : [-1237,-949],
						"4XL" : [-1237,-1281],
						"5XL" : [-1238,-1613],
						"Label" : [-1259.4,761.35]
					}
				},
				"FD_BASE_FB_Y_SS" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_BASE_FB_Y_SS/Converted_Templates/",
					"coords" : 
					{
						"YS" : [-922,-97],
						"YM" : [-923,-342],
						"YL" : [-924,-597],
						"YXL" : [-925,-864],
						"Label" : [-956.37,38.28]
					}
				},
				"FD_BASE_2B_SS" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_BASE_2B_SS/Converted_Templates/",
					"coords" : 
					{
						"S" : [-1283.55,607.96],
						"M" : [-1288.55,315.39],
						"L" : [-1293.55,-0.01],
						"XL" : [-1299.55,-312.77],
						"2XL" : [-1304.55,-634.47],
						"3XL" : [-1309.55,-970.16],
						"4XL" : [-1315.55,-1306.16],
						"5XL" : [-1320.55,-1642.15],
						"Label" : [-1333.55,727.21]
					}
				},
				"FD_BASE_2B_Y_SS" : 
				{
					"path" : "/Volumes/Customization/Library/cads/prepress/FD_BASE_2B_Y_SS/Converted_Templates/",
					"coords" : 
					{
						"YS" : [-1066.6,-106.92],
						"YM" : [-1067.49,-351],
						"YL" : [-1068.36,-605.78],
						"YXL" : [-1069.22,-871.29],
						"Label" : [-1116.6,12.33]
					}
				}
			}


	////////End/////////
	////Data Storage////
	////////////////////
	
	

	///////Begin////////
	///Function Calls///
	////////////////////

	//Script Global Variable Definitions

	var docRef = app.activeDocument;
	var layers = docRef.layers
	var valid = true;

	app.coordinateSystem = CoordinateSystem.ARTBOARDCOORDINATESYSTEM;

	var mrap = "There was an error reading the layers. Please save and relaunch Illustrator";
	var errorList = [];
	var theDocument = {}; 


	
	
	//Check for the existence of 1 or more template layers.
	//Call subsequent functions to move all USA Collars.
	//Alert user to any errors and return if fatal error occurs.

	var existTemplate = isTemplate(layers);

	if(valid && existTemplate)
	{
		//No errors and file is a scriptable template
		var templateList = getTemplates(layers);
		if(!valid)
		{
			sendErrors(errorList);
			return;
		}
		var usaCollars = findUSACollars("template", templateList);
		theDocument.usaCollars = usaCollars;
	}
	else if(valid && !existTemplate)
	{
		//No errors and file is NOT a scriptable template
		var usaCollars = findUSACollars("sel");
		theDocument.usaCollars = usaCollars;
		var templateList = [];


		//***********
		//***TO DO***
		//***********
		//insert function call for scriptUI to populate templateList array

		var cont = true;
		while(cont)
		{
			var theResult = whichGarments();
			if(theResult != null)
				templateList.push(theResult);
		}

	}
	else if(!valid)
	{
		//errors occurred. do not proceed.
		sendErrors(errorList);
		return;
	}

	//check for fatal errors during population of
	//usaCollars array
	if(!valid)
	{
		sendErrors(errorList);
		return;
	}


	//usaCollars array populated succesfully
	//loop templateList to populate theDocument object

	for(var a=0;a<templateList.length;a++)
	{
		var curGarment = templateList[a];
		theDocument["garment" + a] = getObjectData(curGarment,library);
	}

	if(!valid)
	{
		sendErrors(errorList);
		return;
	}

	//move usaCollars to USA Collars layer

	moveUSACollars(theDocument.usaCollars);

	if(!valid)
	{
		sendErrors(errorList);
		return;
	}

	var aBIndex = 0;

	for(key in theDocument)
	{
		docRef.activate();
		docRef.artboards.setActiveArtboardIndex(aBIndex);
		if(key != "usaCollars")
		{
			getNewCollars(theDocument[key].code,theDocument[key].path,theDocument[key].coords, theDocument[key].styleNum)
			aBIndex++;
		}
		
	}


	////////End/////////
	///Function Calls///
	////////////////////



}
container();
